//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VISwpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Briefing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Briefing()
        {
            this.Employees_briefings = new HashSet<Employees_briefings>();
        }
    
        public int ID_briefing { get; set; }
        public System.DateTime Date_briefing { get; set; }
        public string Type_briefing { get; set; }
        public string Cause_briefing { get; set; }
        public string Note_briefing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees_briefings> Employees_briefings { get; set; }
    }
}
