//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VISwpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_briefings
    {
        public int ID_briefing { get; set; }
        public int FK_employee { get; set; }
        public int FK_briefing { get; set; }
    
        public virtual Briefing Briefing { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
