//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VISwpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Full_employees
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Status_empl { get; set; }
        public string Name_division { get; set; }
        public string Name_position { get; set; }
    }
}
