//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VISwpf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDBEntities : DbContext
    {
        public SchoolDBEntities()
            : base("name=SchoolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Briefing> Briefing { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Employees_briefings> Employees_briefings { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Full_employees> Full_employees { get; set; }
    }
}
